[package]
name = "gtt23"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hdf5 = "0.8.1"

[dev-dependencies]
clap = { version = "4.4.7", features = ["derive"] }
ndarray = "0.15.6"

[lib]
name = "gtt23"
path = "src/lib.rs"

[[example]]
name = "dumpcirc"

[[example]]
name = "mkdset"
