name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt update && sudo apt install -y libhdf5-dev hdf5-filter-plugin hdf5-filter-plugin-blosc-serial
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
